version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_PORT=5432  # Ajout de cette ligne pour spécifier le port de la base de données
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb  # Mise à jour avec le nom correct de la base de données
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432

volumes:
  dev-db-data:
